version: "3"

services:

  api:
    image: tokoladang/siplah:symfony0.3
    volumes:
      - ${API_SRC}:/home/siplah/web
    ports:
      - ${API_PORT}:80
    depends_on:
      - db
      - cache

  admin:
    image: tokoladang/siplah:laravel0.2
    volumes:
      - ${ADMIN_SRC}:/home/siplah/web
    ports:
      - ${ADMIN_PORT}:80
    depends_on:
      - db
      - cache

  app:
    image: node:12-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ${APP_SRC}:/home/node/app
    expose:
      - "4200"
    command: "npm start"
    ports:
      - ${APP_PORT}:4200
    depends_on:
      - api

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  cacheadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - ADMIN_USER=${REDIS_ADMIN_USER}
      - ADMIN_PASS=${REDIS_ADMIN_PASS}
      - REDIS_1_HOST=cache
      - REDIS_1_PORT=6379
    ports:
      - ${REDIS_ADMIN_PORT}:80
    depends_on:
      - cache

  db:
    volumes:
      - db:/var/lib/postgresql/data
      - ./database:/initdb
