version: "3"

services:

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    volumes:
      - cache:/data

volumes:
  db:
  cache:
